/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as AceleradorRouteImport } from './routes/acelerador'
import { Route as IndexRouteImport } from './routes/index'

const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const AceleradorRoute = AceleradorRouteImport.update({
  id: '/acelerador',
  path: '/acelerador',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acelerador': typeof AceleradorRoute
  '/gracias': typeof GraciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acelerador': typeof AceleradorRoute
  '/gracias': typeof GraciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acelerador': typeof AceleradorRoute
  '/gracias': typeof GraciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/acelerador' | '/gracias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/acelerador' | '/gracias'
  id: '__root__' | '/' | '/acelerador' | '/gracias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AceleradorRoute: typeof AceleradorRoute
  GraciasRoute: typeof GraciasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acelerador': {
      id: '/acelerador'
      path: '/acelerador'
      fullPath: '/acelerador'
      preLoaderRoute: typeof AceleradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AceleradorRoute: AceleradorRoute,
  GraciasRoute: GraciasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
